baseURL: "https://rustam-lukmanov.com"
title: Rustam A. Lukmanov
paginate: 10
theme: PaperMod


defaultContentLanguage: en
languages:
  en:
    params:
          title: Rustam A. Lukmanov
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true #Swithces on JS scritps and tags


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rustam A. Lukmanov
  description: "Personal website"
  keywords: [Blog, Portfolio, Rustam Lukmanov]
  paginate: 100
  author: Lukmanov R.A.
  # author: ["Me", "You"] # multiple authors
  images: ["/Profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark  # dark,light  
  disableThemeToggle: True
  stickyHeader: True
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  

  ##Search paprams
  params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/circle4.webp"
    favicon16x16: "/circle4.webp"
    favicon32x32: "/circle4.webp"
    apple_touch_icon: "/circle4.webp"
    safari_pinned_tab: "/circle4.webp"

  label:
    text: "Rustam A. Lukmanov"
    icon: /logo_italic7.png
    iconHeight: 35

  # profile-mode
 # profileMode:
    enabled: true # needs to be explicitly set
    title: Hi \U0001f44b there!
    #subtitle: "This is subtitle"
    subtitle: "
    


> ### Hi \U0001f44b I am a Research Scientist. I am interested in scalable, principled methods for analyzing graph data in an unsupervised manner. &nbsp;  


I received Ph.D. \U0001f393 in experimental phyiscs at the University of Bern, advised by Prof. Peter Wurz. I did my masters and bachelors at Saint Petersburg State University in Saint Petersburg, Russia. My M.Sc. advisor was Alexey Goncharov. In Russian, my name reads as Рустам Лукманов.

For publications, see Google Scholar. For code, see GitHub.

Feel free to contact me by email: mail at rustam-lukmanov dot ru.


> Right now I am working on "
    #imageUrl: "/box.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: my image
    buttons:
      - name: Blog
        url: blog
      - name: Publications
        url: publications
      - name: Resume
        url: cv
      - name: Contact Information
        url: contact
  # home-info mode <img src='/images/circle_en_sh2.png' alt='Girl in a jacket' width='400' align='middle'>

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
  homeInfoParams:
    Title: ""

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Home
      name: Home 
      url: /
      weight: 10
    - identifier: Posts
      name: Posts 
      url: /posts/
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: Publications
      name: Publications
      url: /publications/
      weight: 50
    - identifier: CV
      name: CV
      url: /CV/
      weight: 60
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 70
    - identifier: Search
      name: Search
      url: /search/
      weight: 80
    - identifier: Archive
      name: Archive
      url: /archives/
      weight: 40

# TO DO
# Add more content to the website (paper and some parts of the thesis)
# Add a p5JS article